# Generated by Django 5.0.3 on 2024-09-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_item_description_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side'), ('others', 'Others')], default='top', max_length=6, null=True)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(related_name='TrekHeroImages', to='app.item_gallery'),
        ),
    ]
