"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(!572r7hgc*k$qjtfz!za(dkn3@1g^z#sx#c87ma@o3ehbi*6!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# MEDIA_URL is the base public URL for serving media files
MEDIA_URL = '/images/'

# MEDIA_ROOT is the absolute filesystem path where media files are stored
MEDIA_ROOT = os.path.join(BASE_DIR, '/images')



JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "brand_small_text": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-green",
    "navbar": "navbar-gray-dark navbar-dark",
    "navbar_fixed": True,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-blue",
    "sidebar_nav_flat_style": True,
    "theme": "slate",
}


JAZZMIN_SETTINGS = {
    "site_title": "Shop With Tech",
    "site_header": "Tech",
    "site_brand": " Shop With Tech",
    "copyright": "Shop With Tech",
    "welcome_sign": "Shop With Tech",
    # "topmenu_links": [
    #     {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
    #     {"model": "auth.User"},
    #     {"app": "students"},
    #     {"app": "leads"},
    #     {"app": "assets"},
    #     {"app": "performance"},
    #     {"app": "leave"},
    #     {"app": "profiles"},
    
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True, "icon": "fas fa-phone-alt" },
        {"model": "auth.user"}
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "order_with_respect_to": ["leads", "leads.Lead", "leads.LeadFollowUp", "leads.Service", "leads.LeadStatus", "leads.LeadSource", "students","assets","leave", "attendance", "performance", "profiles", "auth"],
    "show_ui_builder": True,
    "changeform_format": "collapsible",
}